/* ========================================
   sample-data.js
   モック用のサンプル入庫カード
   ======================================== */

(function(){
  const today = new Date();
  const ymd = (d) => d.toISOString().slice(0,10);
  const addDays = (d, n) => { const x = new Date(d); x.setDate(x.getDate()+n); return x; };

  state.cards = [
    {
      id: 'c001',
      reserveDate: ymd(today),
      reserveTime: '09:00',
      status: 'check',
      boardId: 'default',
      bayId: null,
      customer: '田中 太郎',
      car: 'ハイエース 平成28年式',
      plate: '品川 500 あ 1234',
      menu: '車検（24ヶ月点検）',
      staff: '佐藤',
      memo: 'タイヤ要相談',
      urgent: false,
    },
    {
      id: 'c002',
      reserveDate: ymd(today),
      reserveTime: '10:00',
      status: 'estim',
      boardId: 'default',
      bayId: 'bay1',
      customer: '山田 花子',
      car: 'N-BOX',
      plate: '練馬 580 う 5678',
      menu: 'オイル交換＋ブレーキ点検',
      staff: '鈴木',
      memo: '',
      urgent: false,
    },
    {
      id: 'c003',
      reserveDate: ymd(today),
      reserveTime: '11:30',
      status: 'parts',
      boardId: 'default',
      bayId: null,
      customer: '小林 隆',
      car: 'プリウス 30系',
      plate: '足立 300 い 9012',
      menu: 'バッテリー交換',
      staff: '高橋',
      memo: 'パーツ明日入荷予定',
      urgent: true,
    },
    {
      id: 'c004',
      reserveDate: ymd(today),
      reserveTime: '13:00',
      status: 'work',
      boardId: 'default',
      bayId: 'bay2',
      customer: '伊藤 真一',
      car: 'アルファード',
      plate: '横浜 300 え 3456',
      menu: 'タイヤ4本組替',
      staff: '佐藤',
      memo: '',
      urgent: false,
    },
    {
      id: 'c005',
      reserveDate: ymd(today),
      reserveTime: '14:00',
      status: 'check',
      boardId: 'import',
      bayId: null,
      customer: '渡辺 恵',
      car: 'BMW 320i',
      plate: '品川 300 お 7890',
      menu: '法定12ヶ月点検',
      staff: '高橋',
      memo: '輸入車対応',
      urgent: false,
    },
    {
      id: 'c006',
      reserveDate: ymd(addDays(today, 1)),
      reserveTime: '09:30',
      status: 'reserved',
      boardId: 'default',
      bayId: null,
      customer: '木村 拓',
      car: 'ヴェルファイア',
      plate: '練馬 300 か 1111',
      menu: '車検',
      staff: '鈴木',
      memo: '',
      urgent: false,
    },
    {
      id: 'c007',
      reserveDate: ymd(addDays(today, 1)),
      reserveTime: '11:00',
      status: 'reserved',
      boardId: 'default',
      bayId: null,
      customer: '吉田 美咲',
      car: 'スイフト',
      plate: '世田谷 580 き 2222',
      menu: 'オイル交換',
      staff: '佐藤',
      memo: '',
      urgent: false,
    },
    // 実績用（過去）
    {
      id: 'c100',
      reserveDate: ymd(addDays(today, -2)),
      reserveTime: '10:00',
      status: 'returned',
      boardId: 'default',
      bayId: 'bay1',
      customer: '青木 守',
      car: 'タント',
      plate: '練馬 580 き 3333',
      menu: 'バッテリー交換',
      staff: '高橋',
      memo: '',
      urgent: false,
      completedAt: ymd(addDays(today, -2)),
    },
    {
      id: 'c101',
      reserveDate: ymd(addDays(today, -3)),
      reserveTime: '14:00',
      status: 'workDone',
      boardId: 'default',
      bayId: null,
      customer: '森下 健',
      car: 'ハリアー',
      plate: '品川 300 く 4444',
      menu: 'ブレーキパッド交換',
      staff: '佐藤',
      memo: '返車待ち',
      urgent: false,
      completedAt: ymd(addDays(today, -3)),
    },
  ];

  // 代車割当サンプル
  state.loanerAssigns = [
    { loanerId: 'L01', cardId: 'c001', fromDate: ymd(today),                toDate: ymd(addDays(today, 2)) },
    { loanerId: 'L02', cardId: 'c003', fromDate: ymd(addDays(today, -1)),   toDate: ymd(addDays(today, 1)) },
    { loanerId: 'L03', cardId: 'c100', fromDate: ymd(addDays(today, -2)),   toDate: ymd(addDays(today, -1)) },
  ];
})();
